on:
  push:
    branches:
      - main

name: helm-chart-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Helm
        uses: azure/setup-helm@v1

      - name: Package Istio Helm Chart
        run: helm package istio -d dist

      - name: Package Gateway Helm Chart
        run: helm package gateway -d dist

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: Release notes here
          draft: false
          prerelease: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
